import {
  Briefcase,
  Camera,
  GraduationCap,
  HeartHandshake,
  Laptop,
  Sparkles,
  Wrench,
} from "lucide-react";
import type { Category, Listing, User } from "@/lib/types";

export const categories: Category[] = [
  { id: "all", label: "הכול", icon: Sparkles },
  { id: "home", label: "תיקונים לבית", icon: Wrench },
  { id: "business", label: "ייעוץ עסקי", icon: Briefcase },
  { id: "wellness", label: "טיפול ויוגה", icon: HeartHandshake },
  { id: "tech", label: "תמיכה טכנית", icon: Laptop },
  { id: "lessons", label: "שיעורים פרטיים", icon: GraduationCap },
  { id: "media", label: "צילום ועיצוב", icon: Camera },
];

export const users: User[] = [
  { id: "u1", name: "יוסי", email: "yossi@example.com", city: "חולון", verified: true },
  { id: "u2", name: "מיכל", email: "michal@example.com", city: "תל אביב", verified: true },
  { id: "u3", name: "אדם", email: "adam@example.com", city: "חיפה", verified: false },
  { id: "u4", name: "נעמה", email: "naama@example.com", city: "ירושלים", verified: true },
  { id: "u5", name: "דניאל", email: "daniel@example.com", city: "באר שבע", verified: true },
  { id: "u6", name: "שרון", email: "sharon@example.com", city: "רמת גן", verified: true },
];

export const listings: Listing[] = [
  {
    id: 1,
    userId: "u1",
    name: "יוסי",
    city: "חולון",
    distance: "4 ק״מ",
    title: "תיקון מזגנים ובדיקת תקלות",
    offer: "מציע שירות תיקון מזגנים לבית ולעסק",
    wants: "מחפש בניית אתר תדמית",
    category: "home",
    tags: ["מזגנים", "שירות לבית", "בארטר מקומי"],
    rating: 4.9,
    verified: true,
    matchScore: 92,
    createdAt: new Date().toISOString(),
  },
  {
    id: 2,
    userId: "u2",
    name: "מיכל",
    city: "תל אביב",
    distance: "2 ק״מ",
    title: "שיעורי יוגה פרטיים בבית או בזום",
    offer: "מציעה 2 שיעורי יוגה מותאמים אישית",
    wants: "מחפשת עיצוב לוגו ומיתוג בסיסי",
    category: "wellness",
    tags: ["יוגה", "בריאות", "אונליין"],
    rating: 4.8,
    verified: true,
    matchScore: 89,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
  },
  {
    id: 3,
    userId: "u3",
    name: "אדם",
    city: "חיפה",
    distance: "7 ק״מ",
    title: "תמיכה טכנית למחשב ולרשת הביתית",
    offer: "מציע התקנות, גיבויים וסידור מחשב איטי",
    wants: "מחפש שיעורי אנגלית לילד בכיתה ו׳",
    category: "tech",
    tags: ["מחשבים", "ראוטר", "טכנאי"],
    rating: 4.7,
    verified: false,
    matchScore: 84,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
  },
  {
    id: 4,
    userId: "u4",
    name: "נעמה",
    city: "ירושלים",
    distance: "3 ק״מ",
    title: "צילום תדמית לעסקים קטנים",
    offer: "מציעה יום צילום קצר כולל 10 תמונות ערוכות",
    wants: "מחפשת ייעוץ עסקי לשיווק ומכירות",
    category: "media",
    tags: ["צילום", "עסקים", "מיתוג"],
    rating: 5,
    verified: true,
    matchScore: 95,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 36).toISOString(),
  },
  {
    id: 5,
    userId: "u5",
    name: "דניאל",
    city: "באר שבע",
    distance: "6 ק״מ",
    title: "שיעורים פרטיים במתמטיקה",
    offer: "מציע 3 שעות תגבור לחטיבה ולתיכון",
    wants: "מחפש תיקוני צבע וצביעה בחדר ילדים",
    category: "lessons",
    tags: ["מתמטיקה", "בגרות", "זום"],
    rating: 4.6,
    verified: true,
    matchScore: 87,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
  },
  {
    id: 6,
    userId: "u6",
    name: "שרון",
    city: "רמת גן",
    distance: "1 ק״מ",
    title: "ייעוץ עסקי לעצמאים",
    offer: "מציעה פגישת מיקוד עסקית של 90 דקות",
    wants: "מחפשת בניית דף נחיתה או אוטומציה פשוטה",
    category: "business",
    tags: ["אסטרטגיה", "שיווק", "עצמאים"],
    rating: 4.9,
    verified: true,
    matchScore: 91,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
  },
];

export const smartMatches = [
  "מצאנו 12 אנשים שמחפשים בדיוק את מה שאת מציעה",
  "יש 4 מודעות קרובות אלייך עם התאמה גבוהה",
  "המערכת ממליצה להתחיל בבארטר של שעה תמורת שעה",
];
